### PR TITLE
Update CameraManager.java

### PR DESCRIPTION
**Pull request by joskarthic**

### CODE REVIEW

**Comment by wildabeast** [comment]
"Update CameraManager.java".

Increasing the MIN_FRAME dimensions. Will this break other people?

**Comment by wildabeast** [comment]
Also should include an new version of the compiled jar (com.google.zxing.client.android.captureactivity.jar).

**Comment by Dbuggerx** [comment]
Care should be taken when changing the frame size. In my "tweaking" experience, I saw that while we can get nice results in high resolution devices, in low resolution devices, it could make the scanner "crash" when the frame size exceeds the available screen space.

**Comment by wildabeast** [comment]
This would be better as a parameter in the options to the scan method.

**Pull request closed without merging**
