### PR TITLE
Add scan options to intent on Android

### PR DESCRIPTION
**Pull request by AxelNennker**
I think this should work but it seems that the scan intent ignores the extras. So feel free to ignore this PR. 
I would have debugged this more but inserting all the LibraryProject files into plugin.xml was to much work.
Would you mind to add a plugin-lib.xml which compiles all the zxing stuff instead of using the jar?

-Axel

### CODE REVIEW

**Comment by jbollacke** [comment]
You have to change the Intent action name from 'com.phonegap.plugins.barcodescanner.SCAN' back to zxing default 'com.google.zxing.client.android.SCAN' or the extras will be ignored.

**Comment by AxelNennker** [comment]
Isn't com.phonegap.plugins.barcodescanner.SCAN a layer above the zxing code?
Do you have a plugin.xml that uses the java code instead of the jar?

**Comment by jbollacke** [comment]
Kind of, yeah. The plugin just writes it into the AndroidManifest.xml as intent-filter for the captureacitivity. In the jar however the 'com.google.zxing.client.android.SCAN' is hardcoded. Changing the plugin to use 'com.google.zxing.client.android.SCAN' works for me. I don't know why wildabeast used his own intent action name. There shouldn't be any conflict with other barcoder scanning apps as the intent is limited to the current (read: the phonegap-app) package.

**Comment by fh-seannicholls** [comment]
We needed to configure the barcode SCAN_WIDTH and SCAN_HEIGHT variables in an Ionic app, so made the above suggested changes. However, because we were using Ng-Cordova we also had to fork Ng-Cordova to make it work - in the end, we can now add any configuration that the com.google.zxing.client.android.SCAN activity accepts.

https://github.com/feedhenry-staff/BarcodeScanner
https://github.com/feedhenry-staff/ng-cordova

**Comment by AxelNennker** [comment]
Hi Sean,
great!
Did you create a pull request? That would make it easiest for @wildabeast to merge it.
I would then close my PR.
Thanks
Axel

**Comment by fh-seannicholls** [comment]
Hi Axel,

I have now done so now at PR #250 

Thanks,
Sean

**Comment by wildabeast** [comment]
Closed in favour of #250.

**Pull request closed without merging**
