### PR TITLE
Introduces universal windows platform, improvements and bugfixing  

### PR DESCRIPTION
**Pull request by sgrebnov**

### CODE REVIEW

**Comment by sgrebnov** [comment]
Could someone please review and merge?

**Comment by mattgrande** [comment]
@wildabeast doesn't seem to be supporting this plugin anymore. There may be a better supported fork, but I haven't found one yet.

**Comment by vladimir-kotikov** [comment]
This is not actual anymore since it will be re-sent to [phonegap repo](https://github.com/phonegap/phonegap-plugin-barcodescanner). @sgrebnov could you plese close it.

**Comment by TimBarham** [comment]
Can this PR be closed now?

**Comment by vladimir-kotikov** [comment]
Yes, it has been merged as https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/1. @sgrebnov, could you please close this?

**Comment by TimBarham** [comment]
Beat him to it :smile:

**Pull request closed without merging**
