### PR TITLE
Fix WP8

### PR DESCRIPTION
**Pull request by sebastieno**
Force the focus of the camera
Fix the plugin when the back button is pressed
Fix the plugin when the app is tombstoned

### CODE REVIEW

**Comment by Delagen** [comment]
+1 to merge, because no way to cancel scanning in current implementation

**Comment by cmgustavo** [comment]
+1 to merge

**Comment by SingleID** [comment]
this is a very important fix to merge ASAP!

**Comment by vladimir-kotikov** [comment]
@sebastieno looks like some part of this functionality was already implemented in https://github.com/wildabeast/BarcodeScanner/pull/226 Could you please rebase your changes to include that PR so we will be able to merge both of them?

**Comment by sebastieno** [comment]
I close this pull request.
I have created a new one into the new official repo (https://github.com/phonegap/phonegap-plugin-barcodescanner)

**Pull request closed without merging**
