### PR TITLE
Windows Phone 8.0 improvements and bugfixes:

### PR DESCRIPTION
**Pull request by sgrebnov**
#615 Adds Cancel button to UI, handle backbutton event
#617 Adds redline focus helper to UI
#618 Adds continuous focusing

### CODE REVIEW

**Comment by sgrebnov** [comment]
Could someone please review and merge?

**Comment by nikhilkh** [comment]
@wildabeast Can you please take a look to see if these changes can be integrated? Ideally we would want to contribute here but we will have to fork this and have Visual Studio reference the forked version if this PR cannot be merged. There is also another related PR: #230,

**Comment by vladimir-kotikov** [comment]
Closing this and re-send to [phonegap repo](https://github.com/phonegap/phonegap-plugin-barcodescanner)

**Comment by Delagen** [comment]
+1

**Comment by TimBarham** [comment]
@sgrebnov and @vladimir-kotikov - are all these changes in the phonegap repo? If so, can we close this PR?

**Comment by vladimir-kotikov** [comment]
Yes, this has been merged as https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/2

**Pull request closed without merging**
